name: Build Working Version

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: https://registry.npmjs.org/
          
    - name: Install lib dependencies
      run: cd lib && npm install
    
    - name: Build library
      run: cd lib && npm run build
    
    - name: Test library
      run: cd lib && npm run test:coverage      